---
# vi: ts=2 sw=2 et:

extraction:
  cpp:
    prepare:
      packages:
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - libpwquality-dev
        - libfdisk-dev
        - libp11-kit-dev
        - libssl-dev
    after_prepare:
      - pip3 install meson
      - export PATH="$HOME/.local/bin/:$PATH"
    before_index:
      # /tmp has `noexec` set in the LGTM infra which breaks meson's
      # compilation checks. Let's temporarily override TMPDIR to /var/tmp which
      # should work as expected
      # See: https://discuss.lgtm.com/t/meson-fails-to-determine-sizes-of-basic-data-types/2639
      - export TMPDIR=/var/tmp
    index:
      build_command:
        - meson build
        - ninja -C build
  python:
    python_setup:
      version: 3
